import {body, param} from "express-validator";

exports.validatePuzzleBody = [
    body().isArray(),
    body('*.puzzle', 'puzzle did not match whitelist').whitelist("0123456789"),
    body('*.puzzle', 'puzzle is not of correct length').isLength({ min: 81, max: 81 }),
    body('*.puzzleSolution', 'puzzle solution did not match whitelist').whitelist("123456789"),
    body('*.puzzleSolution', 'puzzle solution is not of correct length').isLength( { min: 81, max: 81 }),
    body('*.strategyCount.stratOne', 'strategy one is not an integer').isInt(),
    body('*.strategyCount.stratTwo', 'strategy two is not an integer').isInt(),
    body('*.strategyCount.stratThree', 'strategy three is not an integer').isInt(),
    body('*.fastestSolveTime', 'fastest solve time is not an integer').optional().isInt(),
    body('*.averageSolveTime', 'average solve time is not an integer').optional().isInt(),
    body('*.numUsersPlayed', 'num users played is not an integer').optional().isInt(),
    body('*.numTimesPlayed', 'num times played is not an integer').optional().isInt(),
    body('*.trulyUnique', 'truly unique is not a boolean').optional().isBoolean(),
    body('*.drillStrategy', 'drill strategy is not a valid string option').optional().isString().isIn(["stratOne", "stratTwo", "stratThree"]),
    body('*.calendarDate', 'calendar date is not a date').optional().isDate({ strictMode: true, format: "YYYY-MM-DD" }),
    body('*.imageUrl', 'imageUrl is not a string').optional().isString(),
    body('*.description', 'description is not a string').optional().isString(),
];

exports.validatePuzzleParameters = [
    param('id').optional(),
    param('puzzle', 'puzzle did not match whitelist').optional().whitelist("0123456789"),
    param('puzzle', 'puzzle is not of correct length').optional().isLength({ min: 81, max: 81 }),
    param('puzzleSolution', 'puzzle solution did not match whitelist').optional().whitelist("123456789"),
    param('puzzleSolution', 'puzzle solution is not of correct length').optional().isLength( { min: 81, max: 81 }),
    param('strategyCount.stratOne', 'strategy one is not an integer').optional().isInt(),
    param('strategyCount.stratTwo', 'strategy two is not an integer').optional().isInt(),
    param('strategyCount.stratThree', 'strategy three is not an integer').optional().isInt(),
    param('fastestSolveTime', 'fastest solve time is not an integer').optional().isInt(),
    param('averageSolveTime', 'average solve time is not an integer').optional().isInt(),
    param('numUsersPlayed', 'num users played is not an integer').optional().isInt(),
    param('numTimesPlayed', 'num times played is not an integer').optional().isInt(),
    param('trulyUnique', 'truly unique is not a boolean').optional().isBoolean(),
    param('drillStrategy', 'drill strategy is not a valid string option').optional().isString().isIn(["stratOne", "stratTwo", "stratThree"]),
    param('calendarDate', 'calendar date is not a date').optional().isDate({ strictMode: true }),
    param('imageUrl', 'imageUrl is not a string').optional().isString(),
    param('description', 'description is not a string').optional().isString(),
];