import {body, param, query} from "express-validator";

exports.validatePuzzleBody = [
    body().isArray(),
    body('*.puzzle', 'puzzle did not match whitelist').whitelist("0123456789"),
    body('*.puzzle', 'puzzle is not of correct length').isLength({ min: 81, max: 81 }),
    body('*.puzzleSolution', 'puzzle solution did not match whitelist').whitelist("123456789"),
    body('*.puzzleSolution', 'puzzle solution is not of correct length').isLength( { min: 81, max: 81 }),

    body('*.strategyTypes.NAKED_SINGLE', 'NakedSingle strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_SINGLE', 'HiddenSingle strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.NAKED_PAIR', 'NakedPair strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.NAKED_TRIPLET', 'NakedTriplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.NAKED_QUADRUPLET', 'NakedQuadruplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.NAKED_QUINTUPLET', 'NakedQuintuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.NAKED_SEXTUPLET', 'NakedSextuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.NAKED_SEPTUPLET', 'NakedSeptuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.NAKED_OCTUPLET', 'NakedOctuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_PAIR', 'HiddenPair strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_TRIPLET', 'HiddenTriplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_QUADRUPLET', 'HiddenQuadruplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_QUINTUPLET', 'HiddenQuintuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_SEXTUPLET', 'HiddenSextuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_SEPTUPLET', 'HiddenSeptuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.HIDDEN_OCTUPLET', 'HiddenOctuplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.POINTING_PAIR', 'PointingPair strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.POINTING_TRIPLET', 'PointingTriplet strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.BOX_LINE_REDUCTION', 'BoxLineReduction strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.X_WING', 'XWing strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.SWORDFISH', 'Swordfish strategy is not a boolean').optional().isBoolean(),
    body('*.strategyTypes.SINGLES_CHAINING', 'SinglesChaining strategy is not a boolean').optional().isBoolean(),

    body('*.difficulty', "difficulty is not an integer or is not in correct range").isInt({ min: 1, max: 10}),
    body('*.fastestSolveTime', 'fastest solve time is not an integer').optional().isInt(),
    body('*.averageSolveTime', 'average solve time is not an integer').optional().isInt(),
    body('*.numUsersPlayed', 'num users played is not an integer').optional().isInt(),
    body('*.numTimesPlayed', 'num times played is not an integer').optional().isInt(),
    body('*.trulyUnique', 'truly unique is not a boolean').optional().isBoolean(),

    body('*.drillStrategies.NAKED_SINGLE', 'NakedSingle strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_SINGLE', 'HiddenSingle strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.NAKED_PAIR', 'NakedPair strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.NAKED_TRIPLET', 'NakedTriplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.NAKED_QUADRUPLET', 'NakedQuadruplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.NAKED_QUINTUPLET', 'NakedQuintuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.NAKED_SEXTUPLET', 'NakedSextuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.NAKED_SEPTUPLET', 'NakedSeptuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.NAKED_OCTUPLET', 'NakedOctuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_PAIR', 'HiddenPair strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_TRIPLET', 'HiddenTriplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_QUADRUPLET', 'HiddenQuadruplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_QUINTUPLET', 'HiddenQuintuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_SEXTUPLET', 'HiddenSextuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_SEPTUPLET', 'HiddenSeptuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.HIDDEN_OCTUPLET', 'HiddenOctuplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.POINTING_PAIR', 'PointingPair strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.POINTING_TRIPLET', 'PointingTriplet strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.BOX_LINE_REDUCTION', 'BoxLineReduction strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.X_WING', 'XWing strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.SWORDFISH', 'Swordfish strategy is not a boolean').optional().isBoolean(),
    body('*.drillStrategies.SINGLES_CHAINING', 'SinglesChaining strategy is not a boolean').optional().isBoolean(),

    body('*.calendarDate', 'calendar date is not a date').optional().isDate({ strictMode: true, format: "YYYY-MM-DD" }),
    body('*.imageUrl', 'imageUrl is not a string').optional().isString(),
    body('*.description', 'description is not a string').optional().isString(),
];

exports.validatePuzzleParameters = [
    query('id').optional(),
    query('puzzle', 'puzzle did not match whitelist').optional().whitelist("0123456789"),
    query('puzzle', 'puzzle is not of correct length').optional().isLength({ min: 81, max: 81 }),
    query('puzzleSolution', 'puzzle solution did not match whitelist').optional().whitelist("123456789"),
    query('puzzleSolution', 'puzzle solution is not of correct length').optional().isLength( { min: 81, max: 81 }),

    query('strategyTypes.NAKED_SINGLE', 'NakedSingle strategy is not a boolean').optional().isBoolean(),
    query('strategyTypes.HIDDEN_SINGLE', 'HiddenSingle strategy is not a boolean').optional().isBoolean(),
    query('strategyTypes.NAKED_PAIR', 'NakedPair strategy is not a boolean').optional().isBoolean(),
    query('strategyTypes.NAKED_TRIPLET', 'NakedTriplet strategy is not a boolean').optional().isBoolean(),
    query('NAKED_QUADRUPLET', 'NakedQuadruplet strategy is not a boolean').optional().isBoolean(),
    query('NAKED_QUINTUPLET', 'NakedQuintuplet strategy is not a boolean').optional().isBoolean(),
    query('NAKED_SEXTUPLET', 'NakedSextuplet strategy is not a boolean').optional().isBoolean(),
    query('NAKED_SEPTUPLET', 'NakedSeptuplet strategy is not a boolean').optional().isBoolean(),
    query('NAKED_OCTUPLET', 'NakedOctuplet strategy is not a boolean').optional().isBoolean(),
    query('HIDDEN_PAIR', 'HiddenPair strategy is not a boolean').optional().isBoolean(),
    query('HIDDEN_TRIPLET', 'HiddenTriplet strategy is not a boolean').optional().isBoolean(),
    query('HIDDEN_QUADRUPLET', 'HiddenQuadruplet strategy is not a boolean').optional().isBoolean(),
    query('HIDDEN_QUINTUPLET', 'HiddenQuintuplet strategy is not a boolean').optional().isBoolean(),
    query('HIDDEN_SEXTUPLET', 'HiddenSextuplet strategy is not a boolean').optional().isBoolean(),
    query('HIDDEN_SEPTUPLET', 'HiddenSeptuplet strategy is not a boolean').optional().isBoolean(),
    query('HIDDEN_OCTUPLET', 'HiddenOctuplet strategy is not a boolean').optional().isBoolean(),
    query('POINTING_PAIR', 'PointingPair strategy is not a boolean').optional().isBoolean(),
    query('POINTING_TRIPLET', 'PointingTriplet strategy is not a boolean').optional().isBoolean(),
    query('BOX_LINE_REDUCTION', 'BoxLineReduction strategy is not a boolean').optional().isBoolean(),
    query('X_WING', 'XWing strategy is not a boolean').optional().isBoolean(),
    query('SWORDFISH', 'Swordfish strategy is not a boolean').optional().isBoolean(),
    query('SINGLES_CHAINING', 'SinglesChaining strategy is not a boolean').optional().isBoolean(),

    query('difficulty', "difficulty is not an integer or is not in correct range").optional().isInt({ min: 1, max: 10 }),
    query('fastestSolveTime', 'fastest solve time is not an integer').optional().isInt(),
    query('averageSolveTime', 'average solve time is not an integer').optional().isInt(),
    query('numUsersPlayed', 'num users played is not an integer').optional().isInt(),
    query('numTimesPlayed', 'num times played is not an integer').optional().isInt(),
    query('trulyUnique', 'truly unique is not a boolean').optional().isBoolean(),

    query('DRILL_NAKED_SINGLE', 'NakedSingle strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_SINGLE', 'HiddenSingle strategy is not a boolean').optional().isBoolean(),
    query('DRILL_NAKED_PAIR', 'NakedPair strategy is not a boolean').optional().isBoolean(),
    query('DRILL_NAKED_TRIPLET', 'NakedTriplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_NAKED_QUADRUPLET', 'NakedQuadruplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_NAKED_QUINTUPLET', 'NakedQuintuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_NAKED_SEXTUPLET', 'NakedSextuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_NAKED_SEPTUPLET', 'NakedSeptuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_NAKED_OCTUPLET', 'NakedOctuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_PAIR', 'HiddenPair strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_TRIPLET', 'HiddenTriplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_QUADRUPLET', 'HiddenQuadruplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_QUINTUPLET', 'HiddenQuintuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_SEXTUPLET', 'HiddenSextuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_SEPTUPLET', 'HiddenSeptuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_HIDDEN_OCTUPLET', 'HiddenOctuplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_POINTING_PAIR', 'PointingPair strategy is not a boolean').optional().isBoolean(),
    query('DRILL_POINTING_TRIPLET', 'PointingTriplet strategy is not a boolean').optional().isBoolean(),
    query('DRILL_BOX_LINE_REDUCTION', 'BoxLineReduction strategy is not a boolean').optional().isBoolean(),
    query('DRILL_X_WING', 'XWing strategy is not a boolean').optional().isBoolean(),
    query('DRILL_SWORDFISH', 'Swordfish strategy is not a boolean').optional().isBoolean(),
    query('DRILL_SINGLES_CHAINING', 'SinglesChaining strategy is not a boolean').optional().isBoolean(),

    query('calendarDate', 'calendar date is not a date').optional().isDate({ strictMode: true }),
    query('imageUrl', 'imageUrl is not a string').optional().isString(),
    query('description', 'description is not a string').optional().isString(),
];